### ISSUE TITLE
This not a issue just a question

### ISSUE THREAD

**Issue by ysef05** [NocityRP/qb-lift#1]
https://imgur.com/a/ViW6T9h

what kinda target is that (sorry if its a stupid question but i can't sleep without knowing)

**Comment by Prime-Script** [comment]
> https://imgur.com/a/ViW6T9h
> 
> what kinda target is that (sorry if its a stupid question but i can't sleep without knowing)

That is qb-target, made by Berkie but edited by LJ for the No Pixel look but the Box Zone Helper is a personal touch.

**Comment by ysef05** [comment]
oh the box zone helper is not with the target? from LJ 

just knew that the box zone helper is a personal touch because that's what i was looking for but thank you for your time!!!!
